FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/models.py
from baysancompanyblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, unique=True)
    profile_image = db.Column(
        db.String, nullable=False, default='default_profile.png')
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('BlogPost', backref='author', lazy=True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        # daha kullanıcı oluşturulurken passwordu hashliyoruz
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        # burada da kullanıcının şifrelenmiş parloası ile fonksiyona gelen passwordu generate edip karşılaştırıyoruz. Başarılı olursa true gelir
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"Username {self.username}"


class BlogPost(db.Model):
    users = db.relationship(User)
    id = db.Column(db.Integer, primary_key=True, unique=True)
    # __tablename__'i users olan tablonun id kolonunu al
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} -- Date: {self.date} -- Title: {self.title}"

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileAllowed, FileField  # dosya seçimleri için
from flask_login import current_user
from baysancompanyblog.models import User


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo(
        'pass_confirm', message='Passwords must match!')])
    pass_confirm = PasswordField(
        'Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register!')

    def check_email(self, field):
        if User.queryfilter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self, field):
        if User.queryfilter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')


class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[
                        FileAllowed(['jpg', 'png'])])  # jpg veya png dosyaları kabul edilir
    submit = SubmitField('Update')

    def check_email(self, field):
        if User.queryfilter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self, field):
        if User.queryfilter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/__init__.py
# bu sayfada blueprint kütüphanesini import ettiğimiz için tekrar bu sayfada import etmemize gerek yok
from baysancompanyblog.core.views import core
from baysancompanyblog.error_pages.handlers import error_pages
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_migrate import Migrate
from flask_login import LoginManager
app = Flask(__name__)
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + \
    os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
Migrate(app, db)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view('users.login')
app.register_blueprint(core)
app.register_blueprint(error_pages)

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/core/views.py
from flask import render_template, request, Blueprint

# blueprint'e core adını verdik ve bu app ile bağladık
core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/templates/index.html
{% extends 'layout.html' %}
{% block title %}
<title>Home Page</title>
{% endblock %}
{% block body %}
<div class="jumbotron">
    <h1>Baysan Company Blog</h1>
</div>
{% endblock %}

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/templates/info.html
{% extends 'layout.html' %}
{% block title %}
<title>About</title>
{% endblock %}
{% block body %}
<div class="jumbotron">
    <h1>Info about our company</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eveniet eaque recusandae blanditiis ullam porro,
        officiis minus similique eius tempore, numquam laborum repellendus totam, quis quos!</p>
        
</div>
{% endblock %}

FLASK/FlaskBootCamp-Python/XLargeProject-Flask/baysancompanyblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"
        href="{{ url_for('static', filename='node_modules//bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{url_for('static',filename='node_modules//bootstrap/dist/js/bootstrap.min.js')}}">
    <link rel="stylesheet"
        href="{{url_for('static',filename='node_modules//bootstrap/dist/js/bootstrap.bundle.min.js')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='node_modules//jquery/dist/jquery.min.js')}}">
    {% block title %}
    <title>Layout</title>
    {% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('core.index')}}">BaysanCompanyBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{url_for('core.info')}}">About <span
                        class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="#">Log Out</a>
                <a class="nav-item nav-link" href="#">Account</a>
                <a class="nav-item nav-link" href="#">Create Post</a>
                <a class="nav-item nav-link" href="#">Log In</a>
                <a class="nav-item nav-link" href="#">Register</a>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}

        {% endblock %}
    </div>

</body>

</html>