DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.posts_list, name="posts_list"),
    path('post_create/', views.post_create, name="post_create"),
    path('post_detail/<slug:slug>', views.post_detail, name="post_detail"),  # id parametresi alacağını belirttik
    path('post_update/<slug:slug>', views.post_update, name="post_update"),
    path('post_delete/<slug:slug>', views.post_delete, name="post_delete"),
    path('deneme/', views.deneme, name="deneme"),
]

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/django_ileri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import iletisim  # ana url pathinde burayı tanıtacağımız için bu view'i buraya import ediyoruz
from django.conf import global_settings

urlpatterns = [
                  path('jet/', include('jet.urls', 'jet')),
                  path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),  # bu şekilde string şekilde vermeliyiz
                  path('iletisim/', iletisim, name='iletisim'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/blog/models.py
from django.db import models
from django.shortcuts import reverse
from unidecode import unidecode
from django.template.defaultfilters import slugify, safe


class Kategori(models.Model):
    isim = models.CharField(max_length=30, verbose_name='Kategori Adı')

    class Meta:
        verbose_name_plural = 'Kategoriler'
        verbose_name = 'Kategori'

    def __str__(self):
        return self.isim


class Blog(models.Model):  # her model bir tabloya denk gelir. Buradaki 'Blog' aslında bizim tablomuzdur.
    YAYIN_TASLAK = ((None, "Lütfen Bir Değer Seçiniz"), ("yayin", "YAYIN"), ("taslak",
                                                                             "TASLAK"))  # içine tuple'lar alır. Model Form'da option olarak gözükür. ilk parametre değer 2. parametre option'da ne isimle gözükeceği
    title = models.CharField(max_length=100, blank=False, null=True, verbose_name='Başlık',
                             help_text='Başlık Bilgisi Burada Girilir')
    # CharField -> karakter alanı , max_length -> Max karakter uzunluğu zorunludur, verbose_name -> Formda nasıl gözükeceği, help_text -> Formun altında bilgi olarak gözükecek metin, blank -> formda boş girilip girilmemesi, null -> veritabanına boş kayıt edilip edilememesi
    content = models.TextField(max_length=1000, verbose_name='İçerik', null=True, blank=False)
    created_date = models.DateField(auto_now_add=True,
                                    auto_now=False)  # auto_now_add -> oluşturulma tarihini otomatik ekler, auto_now -> Bu nesne her değişime uğradığında otomatik olarak created_date'i güncellenir
    slug = models.SlugField(null=True, unique=True,
                            editable=False)  # editable=False -> admin panelden buraya müdahale edilemez
    kategoriler = models.ManyToManyField(to=Kategori, null=True,
                                         related_name='post')  # bir blog'un birden çok kategorisi olabilir
    image = models.ImageField(verbose_name="Resim", blank=True, null=True, help_text="Kapak Fotoğrafı Seçiniz",
                              default="default/default.png")  # default -> eğer resim yoksa git media/default/default.png yi getir
    yayin_taslak = models.CharField(choices=YAYIN_TASLAK, max_length=7, null=False, blank=True)

    class Meta:  # bu class altına bu modelin tekil ve çoğul isimlerini belirleyebiliriz (admin panelde gözükecek)
        verbose_name = "Gönderi"
        verbose_name_plural = "Gönderiler"
        ordering = [
            'id']  # bu şekilde admin panelinde id'e göre sıralanacak ',' vererek başka bir alan daha verebiliriz

    def __str__(self):  # bu şekilde admin panelinde modelin title'ı gözükecek
        return self.title

    def get_yayin_taslak_durum(self):
        if self.yayin_taslak == "taslak":
            return 'taslak'
        else:
            return 'yayin'

    def get_unique_slug(
            self):  # slug'larımızın düzgün bir şekilde artması için yaptık. Bu sayede sürekli değişecek ve aynı isimde post geldiğinde hata almayacağız
        sayi = 0
        slug = slugify(unidecode(self.title))
        new_slug = slug
        while Blog.objects.filter(slug=new_slug).exists():
            sayi += 1
            new_slug = "{}-{}".format(slug, sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = self.get_unique_slug()
        else:
            post = Blog.objects.get(slug=self.slug)
            if post.title != self.title:
                self.slug = self.get_unique_slug()
        super(Blog, self).save(*args, **kwargs)
        # daha save fonksiyonu işini bitirmeden biz burda override yaptık. Bu sayede modelin slug alanını set ettik.

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/blog/forms.py
from django import forms
from .models import Blog

banned_list = ["menesbaysan@gmail.com", "ysbaysan@gmail.com"]


class IletisimForm(forms.Form):  # formlarında form olması için forms.Form'dan inherit edilmesi gerek
    isim = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=75, label='İsim',
                           required=False)  # label -> formda gözükecek kısım, required -> Zorunlu mu değil mi
    soyisim = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=75, label='Soyisim',
                              required=False)  # widget -> bu field'ın özelliklerini belirliyoruz. class verebiliriz.
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=75, label='Email',
                             required=True)
    email2 = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=75,
                              label='Email Doğrula', required=True)
    icerik = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), max_length=1000, label='İçerik')

    # Yukarıdaki gibi tek tek widgetları belirtmeden bütün widgetları tek fonksiyon ile belirleyebiliriz
    def __init__(self, *args, **kwargs):
        super(IletisimForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control'}
        self.fields['icerik'].widget = forms.Textarea(attrs={'class': 'form-control'})

    def clean_isim(self):  # isim alanı için kontrol yazıyoruz
        isim = self.cleaned_data.get('isim')  # formdan gelen isim değerini çektik
        if isim == 'empty':
            raise forms.ValidationError('{} adında nickname kullanılamaz...'.format('empty'))
        return isim  # mutlaka bir şey return etmeli

    def clean_email(self):  # bu clean'ler ile sadece ilgili alana (email) erişebiliriz. Geri kalana erişemeyiz
        email = self.cleaned_data.get('email')
        if email in banned_list:
            raise forms.ValidationError(
                '{} banlı bir email adresi olduğundan bu adres ile kayıt yapılamaz'.format(email))
        return email

    def clean(self):  # bu bütün formda arama yapar gibi düşünebiliriz
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            self.add_error('email', 'Emailler eşleşmiyor...')  # bunu clean_email altına error olarak ekler
            self.add_error('email2', 'Emailler eşleşmiyor...')
            # raise forms.ValidationError('Emailler eşleşmiyor...')


class BlogForm(forms.ModelForm):  # model formu olması için ModelForm class'ından inherit ediyoruz
    class Meta:
        model = Blog  # bu formun kullanacağı model
        fields = ['title', 'content', 'image', 'yayin_taslak',
                  'kategoriler']  # kullandığı model içerisinde hangi alanlar bu forma gelsin

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control'})
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['kategoriler'].widget.attrs.update({'class': 'form-control'})

    def clean_content(self):
        icerik = self.cleaned_data.get('content')
        if len(icerik) < 10:
            raise forms.ValidationError(
                "Lütfen en az 10 karakter giriniz. Şu anda {} karakter girdiniz..".format(len(icerik)))
        elif (len(icerik) > 1000):
            raise forms.ValidationError(
                "Lütfen en fazla 1000 karakter giriniz. Şu anda {} karakter girdiniz..".format(len(icerik)))
        return icerik

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/blog/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .models import Blog
from .forms import IletisimForm, BlogForm
from django.contrib import messages
from django.http import JsonResponse


def deneme(request):
    if request.is_ajax():  # ajax istekler için bu şekilde kullanmalıyız. eğer method ajax ise
        print("istek geldi")
        return True
    return render(request, 'deneme.html')


def iletisim(request):
    form = IletisimForm(
        data=request.GET or None)  # formumuzdan bir instance oluşturuyoruz, data= -> eğer varsa GET'ten gelenleri al inputlara yerleştir yoksa boş geç
    # print(request.GET.get('email')) # GET içerisindeki değerleri yakalarız
    if form.is_valid():  # eğer formdan gelen bilgiler doğru ise
        isim = form.cleaned_data.get('isim')  # form içindeki bilgileri yakalayabiliyoruz
        soyisim = form.cleaned_data.get('soyisim')
        email = form.cleaned_data.get('email')
        icerik = form.cleaned_data.get('icerik')
        print(icerik, email, isim, soyisim)
    return render(request, 'blog/iletisim.html', {'form': form})  # formu contexte gönderiyoruz


def posts_list(request):
    posts = Blog.objects.all()
    if (request.GET.get('deneme')):
        get = request.GET.get('deneme')
        return render(request,
                      "blog/posts_list.html", context={
                'posts': posts, 'get': get})
    return render(request,
                  "blog/posts_list.html", context={
            'posts': posts})  # ilk önce zorunlu olarak request'i göndermeliyiz, daha sonra template'i daha sonra contexti. context bir sözlüktür


def post_update(request, slug):
    post = get_object_or_404(Blog, slug=slug)
    isim = post.title
    form = BlogForm(request.POST or None,
                    instance=post,
                    files=request.FILES or None)  # instance -> formun datasını verdiğimiz instance ile dolduruyoruz
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        slug = post.slug  # başlık güncellenirse yeni slug'ı seçiyoruz
        messages.success(request, "{} başlıklı post başarıyla güncellendi".format(isim), extra_tags="success")
        return redirect(reverse('blog:post_detail', kwargs={'slug': slug}))
    return render(request, 'blog/post_update.html', context={'form': form, 'post': post})


def post_delete(request, slug):
    post = get_object_or_404(Blog, slug=slug)
    post.delete()
    messages.success(request, "{} başlıklı makale başarıyla silindi".format(post.title), extra_tags="warning")
    return redirect(reverse("blog:posts_list"))


def post_create(request):
    form = BlogForm()
    if request.method == "POST":  # eğer method POST ise
        form = BlogForm(data=request.POST,
                        files=request.FILES or None)  # yeni bir form oluştur ve oluşturduğun formun içine bu datayı yaz
        if form.is_valid():
            created_blog = form.save(
                commit=False)  # commit False olunca oluşacak nesneyi döndürür fakat veritabanına henüz ekleme yapmaz

            created_blog.save()  # commit False yaptığımız için oluşturduğumuz instance'i tekrardan kayıt ediyoruz
            messages.success(request, "{} başlıklı post başarıyla oluşturuldu".format(created_blog.title),
                             extra_tags="success")
            # request'e mesaj yolladık. extra_tags diyerek class vermeyi sağladık
            return redirect(reverse("blog:post_detail",
                                    kwargs={'slug': created_blog.slug}))  # bu sayede parametreli redirect yapabiliriz

    return render(request, 'blog/post_create.html', context={'form': form})


def post_detail(request, slug):  # bir id parametresi alacak dedik
    # blog = Blog.objects.get(pk=id)
    blog = get_object_or_404(Blog,
                             slug=slug)  # eğer bulamazsa 404 döndürür. ilk parametre modelimiz ikinci parametre filtremiz
    return render(request, 'blog/post_detail.html', context={'post': blog})

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/templates/blog/iletisim.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    İletişim
{% endblock title %}
{% block content %}
    <div class="col-lg-6 col-lg-offset-2">
        <div class="pb-2 mt-4 mb-2 border-bottom">
            <h3>İletişim</h3>
        </div>
        <form action="{% url 'iletisim' %}" method="get">
            {% if form.non_field_errors %}
                {% for e in form.non_field_errors %}
                    <span class="text-danger"><b>{{ e }}</b></span>
                {% endfor %}

            {% endif %}
            {% for field in form %} <!-- form içindeki her field -->
                <div class="row">
                    <div class="form-group">
                        <div class="col-lg-2">
                            <label class="control-label">{{ field.label }}</label> <!-- field'ın labeli -->
                        </div>
                        <div class="col-lg-10">
                            {{ field }} <!-- field'ın kendisi -->
                            {% if field.errors %} <!-- eğer field'ın errorları varsa -->
                                {% for error in field.errors %}
                                    <p class="text-danger"><b>{{ error }}</b></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-success btn-sm">
        </form>
    </div>

{% endblock content %}

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/templates/blog/post_create.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    Post Create
{% endblock %}
{% block content %}
    <form action="{% url 'blog:post_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} <!-- csrf token koymazsak hata alırız -->
        {% for field in form %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6">
                        <label class="control-label">
                            <b> {{ field.label }}</b>
                        </label>
                        {{ field }}
                        {% if field.errors %}
                            {% for er in field.errors %}
                                <span> <b>{{ er }}</b></span>
                            {% endfor %}

                        {% else %}
                            {% if field.hep_text %}
                                <b style="color: #666666;">{{ field.help_text }}</b>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="row">
                <div class="col-lg-offset-2 col-lg-2">
                    <button type="submit" class="btn btn-sm btn-success">Gönder</button>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/templates/blog/post_detail.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    Post Detail
{% endblock %}
{% block content %}

    <div class="container" style="margin: 0 auto; width: 505px; padding-top: 90px;">
        <h4 style="color:#6d4a70;"> {{ post.title }} | {% if post.get_yayin_taslak_durum == 'taslak' %}
        <span class="badge badge-warning">{{post.get_yayin_taslak_display}}</span>
            {% else %}
             <span class="badge badge-success">{{post.get_yayin_taslak_display}}</span>
        {% endif %}
            <br><br>
            <div class="pull-right">
                <small>
                    <span style="color: dimgrey;" class="fa fa-clock"></span>{{ post.created_date | timesince }} önce
                    eklendi</small>
                <br><br>
                <a style="color: dimgrey;" href="{% url 'blog:posts_list' %}"><span
                        class="fa fa-home"></span></a>
                <br><br>
                <a style="color: dimgrey;" href="{% url 'blog:post_update' slug=post.slug %}"><span
                        class="fa fa-arrow-up"></span> Güncelle</a>
                <br><br>
                <a style="color: dimgrey;" href="{% url 'blog:post_delete' slug=post.slug %}"><span
                        class="fa fa-eraser"></span> Sil</a>
            </div>
        </h4>
        <hr>
        {% if post.image %}
        <div class="thumbnail">
            <img style="width: %100px;height: 400px;" src="{{ post.image.url }}" alt="">
        </div>
        {% endif %}
        <p>{{ post.content | linebreaks }}</p>
        <small><i class="fa fa-calendar"></i> Kategoriler:
            {% if post.kategoriler.all.count == 0 %}
                Hiç kategori bulunmamaktadır...
            {% else %}
                {{ post.kategoriler.all |join:',' }}
            {% endif %}
        </small>
        <br>
        <small>Slug: {{ post.slug }}</small>
    </div>

{% endblock %}

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/templates/blog/post_update.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    Post Update
{% endblock %}
{% block content %}
    <form action="{% url 'blog:post_update' slug=post.slug %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} <!-- csrf token koymazsak hata alırız -->
        {% for field in form %}
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-6">
                        <label class="control-label">
                            <b> {{ field.label }}</b>
                        </label>
                        {{ field }}
                        {% if field.errors %}
                            {% for er in field.errors %}
                                <span> <b>{{ er }}</b></span>
                            {% endfor %}

                        {% else %}
                            {% if field.hep_text %}
                                <b>{{ field.help_text }}</b>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="row">
                <div class="col-lg-offset-2 col-lg-2">
                    <button type="submit" class="btn btn-sm btn-success">Güncelle</button>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

DJANGO/Django_Temeller_Ileri_Seviye/django_ileri/templates/blog/posts_list.html
{% extends 'layout.html' %} <!-- templates içinden layout'u çağıracak / miras alacak -->
{% load static %}
{% block title %}
    Post List
{% endblock %}
{% block content %}
    <div style="margin: 0 auto; width: 505px;">
        <h1>Posts List <i class="fa fa-book" style="height: 34px;"></i> <a style="color:black;"
                                                                           href="{% url 'blog:post_create' %}"><small
                class="fa-pull-right">Post Create</small></a><a
                style="color:black;"
                href="{% url 'blog:post_create' %}"><span class="fa fa-plus fa-pull-right"></span></a></h1>
        {#        {% if posts.count >= 2 %}#}
        {#            <h3>En Az 2 Adet Post'a sahibiz</h3>#}
        {#        {% endif %}#}
        <hr>
        <br>
        {% for post in posts %}
            <h4><a style="color:#666666;" href="{% url 'blog:post_detail' slug=post.slug %}"> {{ post.title }}</a>
                <span style="color: dimgrey; font-size: 15px;">{{ post.created_date }}
                    <small>{{ post.created_date | timesince }} önce eklendi </small>
                </span>
            </h4>
            <p>{{ post.content |truncatewords:5 }}</p>
        {% empty %} <!-- eğer liste boş dönerse -->
            <b style="color: crimson">Aradığınız kriterde içerik bulunamadı...</b>
        {% endfor %}
        {#        {% if get %}#}
        {#            <h2>{{ get }}</h2>#}
        {#        {% endif %}#}

    </div>
{% endblock %}