DJANGO/fromzerotohero/category/urls.py
from django.urls import path
from category import views

app_name = 'category'

urlpatterns = [
    path('csv/export/', views.export_csv, name="export_csv"),
    path('csv/import/', views.import_csv, name="import_csv"),
]

DJANGO/fromzerotohero/comments/urls.py
from django.urls import path
from comments import views

app_name = 'comments'

urlpatterns = [
    path('list/', views.get_all_comments, name='comment_list'),
    path('add/<int:npk>/', views.add_comment, name='add_comment'),
    path('delete/<int:cpk>/', views.delete_comment, name='delete_comment'),
    path('publish/<int:cpk>/', views.publish_comment, name='publish_comment'),
    path('draft/<int:cpk>/', views.draft_comment, name='draft_comment'),
]

DJANGO/fromzerotohero/fromzerotohero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('news/', include('news.urls')),
                  path('', include('category.urls')),
                  path('', include('subcategory.urls')),
                  path('', include('trending.urls')),
                  path('', include('users.urls')),
                  path('panel/comments/', include('comments.urls')),
                  path('panel/', include('panel.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

DJANGO/fromzerotohero/main/urls.py
from django.urls import path
from django.conf.urls import url
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.my_login, name='my_login'),
    path('register/', views.my_register, name='my_register'),
    path('logout/', views.my_logout, name='my_logout'),
    path('contact/', views.contact, name='contact'),
]

DJANGO/fromzerotohero/panel/urls.py
from django.urls import path
from panel import views

app_name = 'panel'

urlpatterns = [
    path('', views.home, name='home'),
    path('news/list', views.news_list, name='news_list'),
    path('news/add', views.news_add, name='news_add'),
    path('news/delete/<int:pk>', views.news_delete, name='news_delete'),
    path('news/edit/<int:pk>', views.news_edit, name='news_edit'),
    path('category/delete/<int:pk>', views.category_delete, name='category_delete'),
    path('category/list/', views.category_list, name='category_list'),
    path('category/add/', views.category_add, name='category_add'),
    path('subcategory/delete/<int:pk>', views.subcategory_delete, name='subcategory_delete'),
    path('subcategory/list/', views.subcategory_list, name='subcategory_list'),
    path('subcategory/add/', views.subcategory_add, name='subcategory_add'),
    path('sitesettings/', views.site_settings, name='site_settings'),
    path('message_box/', views.message_box, name='message_box'),
    path('trends/list', views.trends, name='trends_list'),
    path('trends/delete/<int:pk>', views.trends_delete, name='trends_delete'),
    path('trends/update/<int:pk>', views.trends_update, name='trends_update'),
    path('trends/add/', views.trend_add, name='trends_add'),
    path('users/change_password/', views.change_pass, name='change_password'),
    path('users/managers/list/', views.manager_list, name='manager_list'),
    path('users/managers/delete/<int:pk>/', views.manager_del, name='manager_delete'),
    path('users/managers/group/list/', views.manager_group_list, name='manager_group_list'),
    path('users/managers/group/add/', views.manager_group_add, name='manager_group_add'),
    path('users/managers/group/delete/<int:pk>/', views.manager_group_del, name='manager_group_delete'),
    path('users/groups/<int:pk>/', views.users_groups, name='users_groups'),
    path('users/groups/add/<int:pk>/', views.users_groups_add, name='users_groups_add'),
    path('users/groups/delete/<int:uid>/<int:gid>/', views.users_groups_delete, name='users_groups_delete'),
    path('users/permissions/list/', views.permission_list, name='permission_list'),
    path('users/permissions/delete/<int:pk>/', views.permission_delete, name='permission_delete'),
    path('users/permissions/user/permission/<int:pk>/', views.users_perms, name='users_permissions'),
    path('users/permissions/user/permission/delete/<int:uid>/<int:pid>/', views.users_perms_delete,
         name='users_permissions_delete'),
    path('users/permissions/user/permission/add/<int:uid>/', views.users_perms_add,
         name='users_permissions_add'),
    path('users/permissions/group/permission/<int:pk>/', views.group_perms, name='group_permissions'),
    path('users/permissions/group/permission/delete/<int:gid>/<int:pid>/', views.group_perms_delete,
         name='group_permissions_delete'),
    path('users/permissions/group/permission/add/<int:gid>/', views.group_perms_add,
         name='group_permissions_add'),
]

DJANGO/fromzerotohero/templates/back/category_list.html
{% extends 'back/layout.html' %}
{% load static %}
{% block body %}
    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>Category List<br><small>you can add, edit and delete your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Category</li>
        <li><a href="{% url 'panel:category_list' %}">Category List</a></li>
    </ul>
    <!-- END Datatables Header -->

    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Export</strong> Data</h2>
        </div>

        <div class="table-responsive">
            <a href="{% url 'category:export_csv' %}" data-toggle="tooltip" title="export csv file"
               class="btn btn-xs btn-primary"> CSV</a>
        </div>
    </div>
    <!-- END Datatables Content -->


    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Import</strong> Data</h2>
        </div>

        <form action="{% url 'category:import_csv' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="table-responsive">
                <input type="file" name="csv_file" id="csv_file"/>
                <br/>
                <button class="btn btn-sm btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <!-- END Datatables Content -->

    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Categories</strong> List</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for cat in categories %}
                    <tr>
                        <td class="text-center">{{ cat.id }}</td>
                        <td class="text-center">{{ cat.name }}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="" data-toggle="tooltip" title="Edit"
                                   class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a>
                                <a href="{% url 'panel:category_delete' pk=cat.pk %}" data-toggle="tooltip"
                                   title="Delete"
                                   class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->
{% endblock body %}
{% block ozel_js %}
    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock ozel_js %}

DJANGO/fromzerotohero/templates/back/change_pass.html
{% extends 'back/layout.html' %}
{% load static %}
{% block ozel_css %}
    <script src="{% static 'node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js' %}"></script>
{% endblock ozel_css %}
{% block body %}
    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>Change Password<br><small>you can change your password!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Users</li>
        <li><a href="{% url 'panel:change_password' %}">Change Password</a></li>
    </ul>
    <!-- END Datatables Header -->

    <!-- Datatables Content -->
    <div class="table-responsive">
        <div class="row">
            <div class="col-md-12">
                <!-- Basic Form Elements Block -->
                <div class="block">
                    <!-- Basic Form Elements Title -->
                    <div class="block-title">
                        <h2><strong>Change</strong> Password</h2>
                    </div>
                    <!-- END Form Elements Title -->

                    <!-- Basic Form Elements Content -->
                    <form action="{% url 'panel:change_password' %}" method="post"
                          enctype="multipart/form-data"
                          id="change_pass_form"
                          class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-6">
                                <input type="password" id="old_pass" name="old_pass"
                                       class="form-control"
                                       placeholder="Old Password">
                            </div>
                            <div class="col-md-6">
                               <input type="password" id="new_pass" name="new_pass"
                                       class="form-control"
                                       placeholder="New Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button id="btn_submit" type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i>
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                    <!-- END Basic Form Elements Content -->
                </div>
                <!-- END Basic Form Elements Block -->
            </div>
        </div>
    </div>
    <!-- END Datatables Content -->
{% endblock body %}
{% block ozel_js %}
    <script src="{% static 'back/js/users/change_pass.js' %}"></script>
{% endblock %}

DJANGO/fromzerotohero/templates/back/comment_list.html
{% extends 'back/layout.html' %}
{% load static %}
{% block body %}
    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>Comment List<br><small>you can view your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Comments</li>
        <li><a href="{% url 'comments:comment_list' %}">List</a></li>
    </ul>
    <!-- END Datatables Header -->

    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Comment</strong> List</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>
                    <th>News</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Is Publish</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for comment in comments %}
                    <tr>
                        <td><a href="{% url 'panel:news_edit' pk=comment.news.pk %}">{{ comment.news.name }}</a></td>
                        <td>{{ comment.name }}</td>
                        <td>{{ comment.email }}</td>
                        <td>{{ comment.txt }}</td>
                        <td class="text-center">
                            {% if comment.is_published == True %}
                                <span class="label label-success">Publish</span>

                            {% else %}
                                <span class="label label-warning">Draft</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <div class="btn-group">
                                {% if comment.is_published == False %}
                                    <a href="{% url 'comments:publish_comment' cpk=comment.pk %}" data-toggle="tooltip"
                                       title="Publish"
                                       class="btn btn-xs btn-default"><i class="fa fa-pencil"></i> Publish</a>
                                {% else %}
                                    <a href="{% url 'comments:draft_comment' cpk=comment.pk %}" data-toggle="tooltip"
                                       title="Draft"
                                       class="btn btn-xs btn-default"><i class="fa fa-pencil"></i> Draft</a>
                                {% endif %}
                                <a href="{% url 'comments:delete_comment' cpk=comment.pk %}" data-toggle="tooltip"
                                   title="Delete"
                                   class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->
{% endblock body %}
{% block ozel_js %}
    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock ozel_js %}

DJANGO/fromzerotohero/templates/back/permission_list.html
{% extends 'back/layout.html' %}
{% load static %}
{% block body %}
    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>Permission List<br><small>you can add, edit and delete your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Permissions</li>
        <li><a href="{% url 'panel:permission_list' %}">List</a></li>
    </ul>
    <!-- END Datatables Header -->
    <div class="row">
        <div class="col-md-12">
            <!-- Basic Form Elements Block -->
            <div class="block">
                <!-- Basic Form Elements Title -->
                <div class="block-title">

                    <h2><strong>Add</strong> Permission</h2>
                </div>
                <!-- END Form Elements Title -->

                <!-- Basic Form Elements Content -->
                <form action="{% url 'panel:permission_list' %}" method="post" enctype="multipart/form-data"
                      class="form-horizontal form-bordered">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-6">
                            <input type="text" id="perm_name" name="perm_name" class="form-control"
                                   placeholder="Permission Name"
                                   required>
                        </div>
                        <div class="col-md-6">
                            <input type="text" id="perm_code_name" name="perm_code_name" class="form-control"
                                   placeholder="Permission Code Name" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <select id="ctypepk" name="ctypepk" class="select-chosen"
                                    data-placeholder="Choose a Group..."
                                    style="width: 250px;">

                                {% for ctype in content_types %}
                                    <option value="{{ ctype.pk }}">{{ ctype.name }}</option>
                                {% endfor %}


                            </select>
                        </div>
                        <div class="col-md-6">

                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i>
                                Submit
                            </button>

                        </div>
                    </div>

                </form>
                <!-- END Basic Form Elements Content -->
            </div>
            <!-- END Basic Form Elements Block -->
        </div>

    </div>

    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Permission</strong> List</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>

                    <th>Name</th>
                    <th>Code</th>
                    <th>Content Type</th>
                    <th>User Count</th>
                    <th>Group Count</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in permissions %}
                    <tr>
                        <td class="text-center">{{ permission.name }}</td>
                        <td class="text-center">{{ permission.codename }}</td>
                        <td class="text-center">{{ permission.content_type }}</td>
                        <td class="text-center">{{ permission.user_set.count }}</td>
                        <td class="text-center">{{ permission.group_set.count }}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="{% url 'panel:permission_delete' pk=permission.pk %}" data-toggle="tooltip"
                                   title="Delete"
                                   class="btn btn-xs btn-danger"><i class="fa fa-times"></i> Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->
{% endblock body %}
{% block ozel_js %}
    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock ozel_js %}

DJANGO/fromzerotohero/templates/back/subcategory_list.html
{% extends 'back/layout.html' %}
{% load static %}
{% block body %}
    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>SubCategory List<br><small>you can add, edit and delete your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>SubCategory</li>
        <li><a href="{% url 'panel:subcategory_list' %}">SubCategory List</a></li>
    </ul>
    <!-- END Datatables Header -->

    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>SubCategories</strong> List</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Category</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for cat in subcategories %}
                    <tr>
                        <td class="text-center">{{ cat.pk }}</td>
                        <td class="text-center">{{ cat.name }}</td>
                        <td class="text-center">{{ cat.category_name }}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="" data-toggle="tooltip" title="Edit"
                                   class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a>
                                <a href="{% url 'panel:subcategory_delete' pk=cat.pk %}" data-toggle="tooltip"
                                   title="Delete"
                                   class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->
{% endblock body %}
{% block ozel_js %}
    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock ozel_js %}

DJANGO/fromzerotohero/templates/back/users_groups.html
{% extends 'back/layout.html' %}
{% load static %}


{% block body %}

    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>User Groups ({{ user.username }})<br><small>you can add, edit and delete your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>User</li>
        <li><a href="{% url 'panel:users_groups' pk=user.manager.pk %}">Groups</a></li>
    </ul>
    <!-- END Datatables Header -->




    <div class="row">
        <div class="col-md-12">
            <!-- Basic Form Elements Block -->
            <div class="block">
                <!-- Basic Form Elements Title -->
                <div class="block-title">

                    <h2><strong>Add User</strong> To Group</h2>
                </div>
                <!-- END Form Elements Title -->

                <!-- Basic Form Elements Content -->
                <form action="{% url 'panel:users_groups_add' pk=user.pk %}" method="post"
                      enctype="multipart/form-data"
                      class="form-horizontal form-bordered">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-6">
                            <select id="group_name" name="group_name" class="select-chosen"
                                    data-placeholder="Choose a Group..."
                                    style="width: 250px;">

                                {% for group in groups %}
                                    <option value="{{ group.pk }}">{{ group.name }}</option>
                                {% endfor %}


                            </select>
                        </div>
                        <div class="col-md-6">

                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i>
                                Submit
                            </button>

                        </div>
                    </div>


                </form>
                <!-- END Basic Form Elements Content -->
            </div>
            <!-- END Basic Form Elements Block -->
        </div>

    </div>


    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Groups</strong> List</h2>
        </div>

        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>

                    <th>Name</th>

                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>

                {% for group in user.groups.all %}
                    <tr>
                        <td>{{ group.name }}</td>

                        <td class="text-center">
                            <div class="btn-group">


                                <a href="{% url 'panel:users_groups_delete' uid=user.pk gid=group.pk %}" data-toggle="tooltip"
                                   title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"> Delete</i></a>

                            </div>
                        </td>
                    </tr>


                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->


{% endblock %}




{% block ozel_js %}

    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock %}

DJANGO/fromzerotohero/templates/back/users_permissions.html
{% extends 'back/layout.html' %}
{% load static %}


{% block body %}

    <!-- Datatables Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-table"></i>User Permissions ({{ user.username }})<br><small>you can add, edit and delete
                your data!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>User</li>
        <li><a href="{% url 'panel:users_permissions' pk=user.pk %}">Permissions</a></li>
    </ul>
    <!-- END Datatables Header -->




    <div class="row">
        <div class="col-md-12">
            <!-- Basic Form Elements Block -->
            <div class="block">
                <!-- Basic Form Elements Title -->
                <div class="block-title">

                    <h2><strong>Add Permission</strong> To User</h2>
                </div>
                <!-- END Form Elements Title -->

                <!-- Basic Form Elements Content -->
                <form action="{% url 'panel:users_permissions_add' uid=user.pk %}" method="post"
                      enctype="multipart/form-data"
                      class="form-horizontal form-bordered">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-6">
                            <select id="perm_pk" name="perm_pk" class="select-chosen"
                                    data-placeholder="Choose a Group..."
                                    style="width: 250px;">

                                {% for perm in all_perms %}
                                    <option value="{{ perm.pk }}">{{ perm.name }}</option>
                                {% endfor %}


                            </select>
                        </div>
                        <div class="col-md-6">

                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i>
                                Submit
                            </button>

                        </div>
                    </div>


                </form>
                <!-- END Basic Form Elements Content -->
            </div>
            <!-- END Basic Form Elements Block -->
        </div>

    </div>


    <!-- Datatables Content -->
    <div class="block full">
        <div class="block-title">
            <h2><strong>Permissions</strong> List</h2>
        </div>

        <div class="table-responsive">
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                <tr>

                    <th>Name</th>
                    <th>Code</th>

                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>

                {% for perm in perms %}
                    <tr>
                        <td>{{ perm.name }}</td>
                        <td>{{ perm.codename }}</td>

                        <td class="text-center">
                            <div class="btn-group">


                                <a href="{% url 'panel:users_permissions_delete' uid=user.pk pid=perm.pk %}"
                                   data-toggle="tooltip"
                                   title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"> Delete</i></a>

                            </div>
                        </td>
                    </tr>


                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->


{% endblock %}




{% block ozel_js %}

    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
    <script>$(function () {
        TablesDatatables.init();
    });</script>
{% endblock %}