DJANGO/fromzerotohero/fromzerotohero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('news/', include('news.urls')),
                  path('', include('category.urls')),
                  path('', include('subcategory.urls')),
                  path('', include('trending.urls')),
                  path('', include('users.urls')),
                  path('panel/comments/', include('comments.urls')),
                  path('panel/', include('panel.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

DJANGO/fromzerotohero/main/urls.py
from django.urls import path
from django.conf.urls import url
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.my_login, name='my_login'),
    path('register/', views.my_register, name='my_register'),
    path('logout/', views.my_logout, name='my_logout'),
    path('contact/', views.contact, name='contact'),
]

DJANGO/fromzerotohero/panel/urls.py
from django.urls import path
from panel import views

app_name = 'panel'

urlpatterns = [
    path('', views.home, name='home'),
    path('news/list', views.news_list, name='news_list'),
    path('news/add', views.news_add, name='news_add'),
    path('news/delete/<int:pk>', views.news_delete, name='news_delete'),
    path('news/edit/<int:pk>', views.news_edit, name='news_edit'),
    path('category/delete/<int:pk>', views.category_delete, name='category_delete'),
    path('category/list/', views.category_list, name='category_list'),
    path('category/add/', views.category_add, name='category_add'),
    path('subcategory/delete/<int:pk>', views.subcategory_delete, name='subcategory_delete'),
    path('subcategory/list/', views.subcategory_list, name='subcategory_list'),
    path('subcategory/add/', views.subcategory_add, name='subcategory_add'),
    path('sitesettings/', views.site_settings, name='site_settings'),
    path('message_box/', views.message_box, name='message_box'),
    path('trends/list', views.trends, name='trends_list'),
    path('trends/delete/<int:pk>', views.trends_delete, name='trends_delete'),
    path('trends/update/<int:pk>', views.trends_update, name='trends_update'),
    path('trends/add/', views.trend_add, name='trends_add'),
    path('users/change_password/', views.change_pass, name='change_password'),
    path('users/managers/list/', views.manager_list, name='manager_list'),
    path('users/managers/delete/<int:pk>/', views.manager_del, name='manager_delete'),
    path('users/managers/group/list/', views.manager_group_list, name='manager_group_list'),
    path('users/managers/group/add/', views.manager_group_add, name='manager_group_add'),
    path('users/managers/group/delete/<int:pk>/', views.manager_group_del, name='manager_group_delete'),
    path('users/groups/<int:pk>/', views.users_groups, name='users_groups'),
    path('users/groups/add/<int:pk>/', views.users_groups_add, name='users_groups_add'),
    path('users/groups/delete/<int:uid>/<int:gid>/', views.users_groups_delete, name='users_groups_delete'),
    path('users/permissions/list/', views.permission_list, name='permission_list'),
    path('users/permissions/delete/<int:pk>/', views.permission_delete, name='permission_delete'),
    path('users/permissions/user/permission/<int:pk>/', views.users_perms, name='users_permissions'),
    path('users/permissions/user/permission/delete/<int:uid>/<int:pid>/', views.users_perms_delete,
         name='users_permissions_delete'),
    path('users/permissions/user/permission/add/<int:uid>/', views.users_perms_add,
         name='users_permissions_add'),
    path('users/permissions/group/permission/<int:pk>/', views.group_perms, name='group_permissions'),
    path('users/permissions/group/permission/delete/<int:gid>/<int:pid>/', views.group_perms_delete,
         name='group_permissions_delete'),
    path('users/permissions/group/permission/add/<int:gid>/', views.group_perms_add,
         name='group_permissions_add'),
]

DJANGO/fromzerotohero/main/models.py
from django.db import models


class Main(models.Model):
    name = models.CharField(max_length=255)
    about = models.TextField()
    facebook_address = models.CharField(max_length=255)
    twitter_address = models.CharField(max_length=255)
    youtube_address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    link_name = models.CharField(max_length=255)
    set_name = models.CharField(max_length=255)
    pic_url = models.TextField(default='-')
    pic_name = models.TextField(default='-')

    def __str__(self):
        return self.set_name + " ({})".format(self.id)


class ContactForm(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True, blank=False)
    is_it_read = models.BooleanField(default=False)

    def __str__(self):
        return self.name

DJANGO/fromzerotohero/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Main, ContactForm
from news.models import News
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.contrib.auth.models import User
from users.models import Manager,CustomUser
from ipware import get_client_ip
from ip2geotools.databases.noncommercial import DbIpCity


def home(request):
    news = News.objects.all().order_by('-date')  # büyükten küçüğe sıralar
    context = {
        'news': news,
    }
    return render(request, 'front/home.html', context=context)


def about(request):
    news = News.objects.all()
    context = {
        'news': news,
    }
    return render(request, 'front/about.html', context=context)


def my_login(request):
    if request.method == "POST":
        username = request.POST.get('login_username')
        password = request.POST.get('login_password')
        if username != "" and password != "":
            user = authenticate(username=username, password=password)  # user'i doğruladık
            if user != None:  # eğer user nesnesi varsa
                login(request, user)  # login yaptık
                return redirect('panel:home')
    return render(request, 'front/login.html')


def my_logout(request):
    logout(request)
    return redirect('main:my_login')


def contact(request):
    if request.method == "POST" and request.is_ajax():
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        try:
            contact_form = ContactForm(name=name, email=email, message=message)
            contact_form.save()
            data = {
                'success': True
            }
        except:
            data = {
                'error': 'Database Registry Error!'
            }
        return JsonResponse(data)
    news = News.objects.all()
    context = {
        'news': news,
    }
    return render(request, 'front/contact.html', context=context)


def my_register(request):
    if request.method == "POST":
        username = request.POST.get("new_username")
        name = request.POST.get("new_name")
        email = request.POST.get("new_email")
        password = request.POST.get("new_password")
        password_verify = request.POST.get("new_password_verify")
        if password != password_verify or len(password) < 3:
            error = "Your password not verified or password < 3 character!"
            link = request.META.get('HTTP_REFERER')
            context = {
                'error': error,
                'link': link
            }
            return render(request, 'front/msgbox.html', context=context)
        if len(User.objects.filter(username=username)) == 0 and len(User.objects.filter(email=email)) == 0:
            # user = User(username=username, email=email, password=password)
            # user.save()
            (ip, is_routable) = get_client_ip(request)
            if ip is None:
                ip = '0.0.0.0'
            # else:
            #     if is_routable:
            #         ipv = 'Public'
            #     else:
            #         ipv = 'Private'
            try:
                response = DbIpCity.get(ip, api_key='free')
                country = response.country + " | " + response.city
            except:
                country = "Unkown"
            user = User.objects.create_user(username=username, first_name=username, email=email,
                                            password=password)  # iki türlü de user oluşturabiliriz
            manager = Manager(name=name, user=user, email=email, ip=ip, country=country)
            manager.save()
            return redirect('main:my_login')
        else:
            error = "Your Email or Username has been used!"
            link = request.META.get('HTTP_REFERER')
            context = {
                'error': error,
                'link': link
            }
            return render(request, 'front/msgbox.html', context=context)
    return render(request, 'front/login.html')

DJANGO/fromzerotohero/main/templates/back/includes/sidebar.html
{% load static %}
<ul class="sidebar-nav">
    <li>
        <a href="{% url 'panel:home' %}" class=" active"><i
                class="gi gi-stopwatch sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
    </li>
    <li class="sidebar-header">
                            <span class="sidebar-header-options clearfix"><a href="javascript:void(0)"
                                                                             data-toggle="tooltip"
                                                                             title="Quick Settings"><i
                                    class="gi gi-settings"></i></a></span>
        <span class="sidebar-header-title">Site Settings</span>
    </li>
    <li>
        <a href="#" class="sidebar-nav-menu"><i
                class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i
                class="gi gi-show_big_thumbnails sidebar-nav-icon"></i><span
                class="sidebar-nav-mini-hide">Categories</span></a>
        <ul>
            <li>
                <a href="{% url 'panel:category_add' %}">Add Category</a>
            </li>
            <li>
                <a href="{% url 'panel:category_list' %}">Categories List</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#" class="sidebar-nav-menu"><i
                class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i
                class="gi gi-show_big_thumbnails sidebar-nav-icon"></i><span
                class="sidebar-nav-mini-hide">SubCategories</span></a>
        <ul>
            <li>
                <a href="{% url 'panel:subcategory_add' %}">Add SubCategory</a>
            </li>
            <li>
                <a href="{% url 'panel:subcategory_list' %}">SubCategories List</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#" class="sidebar-nav-menu"><i
                class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i
                class="gi gi-show_big_thumbnails sidebar-nav-icon"></i><span
                class="sidebar-nav-mini-hide">News</span></a>
        <ul>
            <li>
                <a href="{% url 'panel:news_add' %}">Add News</a>
            </li>
            <li>
                <a href="{% url 'panel:news_list' %}">News List</a>
            </li>
        </ul>
    </li>
</ul>
<!-- END Sidebar Navigation -->